<a href="https://colab.research.google.com/github/KIMAYASETHI/InHerit-genetic-compatibility/blob/main/Copy_of_Python_for_Biologists_by_Kimaya_Sethi_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Biologists: Lists, Tuples & Dictionaries

By the end of the session, I was able to:

1.   Create and access a list
2.   Add, remove, and modify items in a list
3. Understand indexing
4. Create and access tuples
5. Explain why a tuple is different from a list
6. Create dictionaries using key → value
7. Retrieve, add, modify, and delete dictionary information
8. Apply all three structures to simple biological datasets

Suppose I give you the names of 5 bacteria. How would you store them?


```
E. coli
Bacillus subtilis
Staphylococcus aureus
Salmonella
Lactobacillus
```

Python needs ways to store multiple pieces of information together

 | Python structure | Think of it as       |
| ---------------- | -------------------- |
| List             | A shopping list      |
| Tuple            | A fixed label/record |
| Dictionary       | A contact book       |

# Lists

**A list is simply a collection of items kept together in a particular order.**

In [ ]:
#creating a list
bacteria = ["E. coli", "Bacillus", "Salmonella", "Lactobacillus"]

In [ ]:
#printing a list
bacteria

['E. coli', 'Bacillus', 'Salmonella', 'Lactobacillus']

In [ ]:
#accessing list items
print(bacteria[2])

Salmonella

In [ ]:
bacteria[1:3]

[]

In [ ]:
#accessing list items
print(bacteria[2])

Salmonella

In [ ]:
#changing a list
bacteria = ["E. coli", "Bacillus", "Salmonella"]
bacteria

['E. coli', 'Bacillus', 'Salmonella']

In [ ]:
#changing list item
bacteria[1] = "Staphylococcus"
print(bacteria)

['E. coli', 'Staphylococcus', 'Salmonella']

In [ ]:
#adding list item.
#append means put one more item at the end
bacteria.append("Lactobacillus")
print(bacteria)

['E. coli', 'Staphylococcus', 'Salmonella', 'Lactobacillus']

In [ ]:
#removing list items
bacteria.remove("Lactobacillus")
print(bacteria)

['E. coli', 'Staphylococcus', 'Salmonella']

In [ ]:
#removing list items
bacteria.pop()
bacteria

IndexError: pop from empty list



```
remove() → remove a specific item
pop() → remove an item, normally from the end, but you can remove items using it's index as well
```

In [ ]:
#another example
numbers = [10, 20, 30, 40, 50]
numbers.pop(2)

print(numbers)

[10, 20, 40, 50]
30

In [ ]:
#another way of removing an item using del
numbers = [10, 20, 30, 40, 50]

# Delete the element at index 2 (the number 30)
del numbers[2]

print(numbers)

[10, 20, 40, 50]

In [ ]:
numbers = [10, 20, 30, 40, 50]

# Remove elements from index 1 up to (but not including) index 4
del numbers[1:4]

print(numbers)

[10, 50]

# Exercise 1: Simple General Hands-on — Shopping List
Create a shopping list containing:

1.   Milk
2.   Bread
3. Eggs
4. Rice

Then:



*   Print the list.
*   Print the first item.
* Print the first item.
* Change "Rice" to "Pasta".
* Remove "Bread".
* Print the final list.

# Exercise 2: List of organisms



```
organisms = [
    "E. coli",
    "Bacillus subtilis",
    "Staphylococcus aureus",
    "Salmonella"
]

print(organisms)
```
* Print the first organism.
* Print the third organism.
* Add "Lactobacillus".
* Replace "Salmonella" with "Pseudomonas aeruginosa".
* Remove "Bacillus subtilis".

# Exercise 3: Biological Exercise: Gene list



1.   Create a list with these items - "BRCA1", "TP53", "EGFR", "MYC"
2.   Which gene is at position 2?
3. Add "KRAS" gene
4. Remove "MYC"

#TUPLES
Sometimes we have a collection of information that should NOT be changed.

Example: (latitude, longitude), (sample_id, temperature), etc.



```
A tuple uses parentheses.
coordinates = (10.5, 76.2)
```

List versus Tuples

**List**

A shopping list:

    You can add/remove/change things.

**Tuple**

A date of birth:

    It is a fixed piece of information.

In [ ]:
#defining a tuple
dob = (15, 8, 2001)

In [ ]:
#accessing a tuple
print(dob[0])

15

In [ ]:
#execute this and see the output
dob[0] = 20

In [ ]:
#another example
dimensions = (10, 20, 30)

print(dimensions)
print(dimensions[0])
print(dimensions[1])

(10, 20, 30)
10
20

**Lists are mutable. Tuples are immutable**

In [ ]:
#another example
sample = ("S001", "E. coli", 37)

#S001       → Sample ID
#E. coli    → Organism
#37         → Temperature

In [ ]:
print(sample[0])
print(sample[1])
print(sample[2])

S001
E. coli
37

In [ ]:
sample[0] = "demo"

TypeError: 'tuple' object does not support item assignment

Difference between List and Tuples

| Feature               | List                        | Tuple                        |
| --------------------- | --------------------------- | ---------------------------- |
| Brackets              | `[ ]`                       | `( )`                        |
| Ordered?              | Yes                         | Yes                          |
| Can change items?     | **Yes**                     | **No**                       |
| Can add/remove items? | **Yes**                     | **No**                       |
| Example               | `genes = ["BRCA1", "TP53"]` | `coordinates = (10.5, 76.2)` |
| Best analogy          | Shopping list               | Fixed record                 |

In [ ]:
#LIST

genes = ["BRCA1", "TP53", "MYC"]

genes[0] = "EGFR"

print(genes)

In [ ]:
#Tuple

coordinates = (10.5, 76.2)

coordinates[0] = 11.0



```
# List → ordered + changeable

# Tuple → ordered + unchangeable
```

# Dictionary

A dictionary stores information as a KEY → VALUE pair.

In [ ]:
#Think of it like a biological sample record.
#Instead of remembering that the organism is the second item, you give that information a meaningful name.

sample = {
    "sample_id": "S101",
    "organism": "E. coli",
    "temperature": 37,
    "pH": 7.0
}

In [ ]:
print(sample)

{'sample_id': 'S101', 'organism': 'E. coli', 'temperature': 37, 'pH': 7.0}

KEY             VALUE
-------------------------
**sample_id   →   S101**

**organism    →   E. coli**

**temperature →   37**

**pH          →   7.0**

In [ ]:
#With a list, we use a position:
organisms = ["E. coli", "Bacillus", "Salmonella"]
print(organisms[0])

E. coli

In [ ]:
#With a dictionary, we use a key:
print(sample["temperature"])

37

**List → "Give me item number 1."**
**Dictionary → "Give me the value associated with 'organism'."**

In [ ]:
#managing entries in a dictionary


#We can change a value:
sample["pH"] = 7.2

In [ ]:
sample["gram_stain"] = "Gram-negative"

In [ ]:
sample

{'sample_id': 'S101',
 'organism': 'E. coli',
 'pH': 7.2,
 'gram_stain': 'Gram-negative'}

In [ ]:
#removing item
del sample["temperature"]

# **Exercise**

bacteria = {

    "E_coli": "Gram-negative",

    "B_subtilis": "Gram-positive",

    "S_aureus": "Gram-positive",

    "Salmonella": "Gram-negative"
}

1. What is the Gram reaction of E. coli?
2. What is the Gram reaction of Salmonella?
3. Add Pseudomonas:
4. Print the complete dictionary:

# **Handling arrays and basic matrix operations with libraries like NumPy**

In [ ]:
#Suppose we measured the growth of a bacterial culture over five hours:
growth = [12, 18, 25, 31, 40]

**What if we want to add 5 to every measurement?**

In [ ]:
growth + 5

**This does not do what we want.**

# Introducing NumPy

**NumPy is a Python library designed for working with numerical data.**

In [ ]:
#importing numpy library
import numpy as np

In [ ]:
#now use numpy
growth = np.array([12, 18, 25, 31, 40])
print(growth)

[12 18 25 31 40]

**Why NumPy arrays?**

In [ ]:
print(growth + 5)

[17 23 30 36 45]

**NumPy has added 5 to every element.**

In [ ]:
print(growth * 2)

[24 36 50 62 80]

**NumPy has multiplied every element with 2**

In [ ]:
measurements = np.array([10, 20, 30, 40, 50])

In [ ]:
print(measurements + 10)
print(measurements - 5)
print(measurements * 2)
print(measurements / 10)

[20 30 40 50 60]
[ 5 15 25 35 45]
[ 20  40  60  80 100]
[1. 2. 3. 4. 5.]

**Statistical Functions**

In [ ]:
print(np.sum(measurements))
print(np.mean(measurements))
print(np.max(measurements))
print(np.min(measurements))

150
30.0
50
10

**Indexing Arrays**

In [ ]:
growth = np.array([12, 18, 25, 31, 40])

print(growth[0])
print(growth[2])
print(growth[4])

12
25
40

In [ ]:
print(growth[-1])

40

# **Exercise**

In [ ]:
temperature = np.array([25, 27, 29, 31, 33])


1.   Print the first temperature.
2.  Print the last temperature.
3. Add 2°C to every temperature.
4. Calculate the average temperature.
5. Find the highest temperature.
6. Find the lowest temperature.

**Biological application: bacterial growth**

In [ ]:
#Suppose optical density (OD600) was measured during bacterial growth:
od = np.array([0.10, 0.18, 0.32, 0.55, 0.82, 1.10])

In [ ]:
#What was the average OD?
print(np.mean(od))

0.5116666666666667

In [ ]:
#What was the maximum OD?
print(np.max(od))

1.1

In [ ]:
#How much did OD increase from the first to the last measurement?
increase = od[-1] - od[0]

print(increase)

1.0

**Array comparisons**

In [ ]:


print(od > 0.5)

#NumPy can check every measurement against a condition

[False False False  True  True  True]

In [ ]:
print(od[od > 0.5])

[0.55 0.82 1.1 ]

**Filtering with NumPy**

In [ ]:
import numpy as np
colony_counts = np.array([45, 120, 250, 80, 310, 175])

high_counts = colony_counts[colony_counts != 250]

print(high_counts)

[ 45 120  80 310 175]

# **Matrices**
So far we had one row of numbers. What if we have several rows and columns?

For example, bacterial growth measured for three organisms:

In [ ]:
growth = np.array([
    [0.10, 0.20, 0.35, 0.50],
    [0.15, 0.30, 0.45, 0.60],
    [0.08, 0.18, 0.30, 0.42]
])

In [ ]:
print(growth)

[[0.1  0.2  0.35 0.5 ]
 [0.15 0.3  0.45 0.6 ]
 [0.08 0.18 0.3  0.42]]

In [ ]:
print(growth.shape)

(3, 4)

In [ ]:
print(growth.ndim)

2

In [ ]:
print(growth.size)

12

**Accessing elements in a matrix**

In [ ]:
growth[0, 0]

np.float64(0.1)

In [ ]:
growth[1, 2]

np.float64(0.45)

**Accessing an entire row**

In [ ]:
print(growth[0])

[0.1  0.2  0.35 0.5 ]

In [ ]:
print(growth[1])

[0.15 0.3  0.45 0.6 ]

**Accessing a column**

In [ ]:
print(growth[:, 0])

#:  → all rows
#0  → column 0

In [ ]:
growth[:, 2]

# **Loading an external dataset** - introducing Pandas Library

In [ ]:
#importing library
import pandas as pd

In [ ]:
#reading the file (external)
data = pd.read_csv("dataset.csv")

In [ ]:
#printing the data
data

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
0,S001,P. aeruginosa,Food,LB Agar,37,7.01,36,250,1.18,1.45,Tetracycline,19.2
1,S002,L. monocytogenes,Clinical,LB Agar,25,7.82,36,209,0.60,1.24,Gentamicin,19.9
2,S003,B. subtilis,Clinical,LB Agar,42,7.13,18,244,0.96,1.27,Gentamicin,19.3
3,S004,L. monocytogenes,Soil,LB Agar,30,7.79,48,140,0.71,0.81,Tetracycline,21.9
4,S005,L. monocytogenes,Food,Mannitol Salt Agar,25,7.63,18,135,0.69,0.94,Ampicillin,16.5
5,S006,S. aureus,Fermentation,LB Agar,42,6.62,48,252,1.00,1.43,Tetracycline,19.2
6,S007,B. subtilis,Food,Nutrient Agar,42,5.74,36,278,0.91,1.52,Ampicillin,22.6
7,S008,B. subtilis,Fermentation,MacConkey Agar,42,6.43,36,217,0.85,1.27,Gentamicin,20.1
8,S009,B. subtilis,Soil,LB Agar,25,7.17,36,156,0.76,0.93,Ampicillin,25.4
9,S010,L. monocytogenes,Water,LB Agar,25,7.16,24,184,0.53,1.08,Ampicillin,19.2
10,S011,P. aeruginosa,Clinical,Mannitol Salt Agar,25,6.98,48,244,0.70,1.35,Ampicillin,16.6
11,S012,B. subtilis,Soil,LB Agar,37,6.19,24,253,1.29,1.40,Gentamicin,17.9
12,S013,L. monocytogenes,Clinical,LB Agar,25,6.90,24,191,0.57,1.25,Gentamicin,18.2
13,S014,S. aureus,Water,LB Agar,25,6.46,18,171,0.56,1.06,Ampicillin,19.0
14,S015,P. aeruginosa,Water,Mannitol Salt Agar,25,7.93,24,179,0.57,0.96,Ampicillin,24.6
15,S016,S. aureus,Soil,LB Agar,37,7.62,18,115,1.10,0.93,Tetracycline,28.8
16,S017,P. aeruginosa,Water,MacConkey Agar,25,7.30,18,252,0.51,1.26,Ampicillin,19.2
17,S018,L. monocytogenes,Fermentation,Mannitol Salt Agar,42,6.09,24,199,0.89,1.24,Tetracycline,16.2
18,S019,E. coli,Water,MacConkey Agar,25,6.14,48,132,0.49,0.94,Ampicillin,25.4
19,S020,P. aeruginosa,Clinical,Mannitol Salt Agar,42,5.60,48,71,0.87,0.60,Tetracycline,21.5
20,S021,S. aureus,Clinical,LB Agar,42,7.28,48,287,0.87,1.61,Gentamicin,15.2
21,S022,L. monocytogenes,Clinical,MacConkey Agar,42,5.78,48,132,0.98,0.96,Ampicillin,24.8
22,S023,P. aeruginosa,Clinical,Mannitol Salt Agar,37,6.60,48,120,1.10,0.96,Ampicillin,22.8
23,S024,E. coli,Fermentation,Nutrient Agar,37,6.00,24,132,1.07,1.09,Ampicillin,20.3
24,S025,E. coli,Food,LB Agar,37,7.74,24,100,1.19,0.81,Ampicillin,24.5
25,S026,B. subtilis,Soil,Mannitol Salt Agar,25,6.69,36,206,0.53,1.09,Tetracycline,21.1
26,S027,B. subtilis,Clinical,Nutrient Agar,42,6.91,48,132,0.98,0.85,Ampicillin,29.7
27,S028,S. aureus,Water,Mannitol Salt Agar,37,7.24,24,21,1.28,0.46,Gentamicin,24.8
28,S029,P. aeruginosa,Clinical,Nutrient Agar,37,5.85,36,149,0.96,0.98,Gentamicin,20.4
29,S030,P. aeruginosa,Water,LB Agar,25,7.01,48,239,0.67,1.33,Ampicillin,19.3

In [ ]:
#only printing the first 5 rows
data.head()

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
0,S001,P. aeruginosa,Food,LB Agar,37,7.01,36,250,1.18,1.45,Tetracycline,19.2
1,S002,L. monocytogenes,Clinical,LB Agar,25,7.82,36,209,0.60,1.24,Gentamicin,19.9
2,S003,B. subtilis,Clinical,LB Agar,42,7.13,18,244,0.96,1.27,Gentamicin,19.3
3,S004,L. monocytogenes,Soil,LB Agar,30,7.79,48,140,0.71,0.81,Tetracycline,21.9
4,S005,L. monocytogenes,Food,Mannitol Salt Agar,25,7.63,18,135,0.69,0.94,Ampicillin,16.5

In [ ]:
#printing last 5 records
data.tail()

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
25,S026,B. subtilis,Soil,Mannitol Salt Agar,25,6.69,36,206,0.53,1.09,Tetracycline,21.1
26,S027,B. subtilis,Clinical,Nutrient Agar,42,6.91,48,132,0.98,0.85,Ampicillin,29.7
27,S028,S. aureus,Water,Mannitol Salt Agar,37,7.24,24,21,1.28,0.46,Gentamicin,24.8
28,S029,P. aeruginosa,Clinical,Nutrient Agar,37,5.85,36,149,0.96,0.98,Gentamicin,20.4
29,S030,P. aeruginosa,Water,LB Agar,25,7.01,48,239,0.67,1.33,Ampicillin,19.3

In [ ]:
#printing first 10 rows
data.head(10)

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
0,S001,P. aeruginosa,Food,LB Agar,37,7.01,36,250,1.18,1.45,Tetracycline,19.2
1,S002,L. monocytogenes,Clinical,LB Agar,25,7.82,36,209,0.60,1.24,Gentamicin,19.9
2,S003,B. subtilis,Clinical,LB Agar,42,7.13,18,244,0.96,1.27,Gentamicin,19.3
3,S004,L. monocytogenes,Soil,LB Agar,30,7.79,48,140,0.71,0.81,Tetracycline,21.9
4,S005,L. monocytogenes,Food,Mannitol Salt Agar,25,7.63,18,135,0.69,0.94,Ampicillin,16.5
5,S006,S. aureus,Fermentation,LB Agar,42,6.62,48,252,1.00,1.43,Tetracycline,19.2
6,S007,B. subtilis,Food,Nutrient Agar,42,5.74,36,278,0.91,1.52,Ampicillin,22.6
7,S008,B. subtilis,Fermentation,MacConkey Agar,42,6.43,36,217,0.85,1.27,Gentamicin,20.1
8,S009,B. subtilis,Soil,LB Agar,25,7.17,36,156,0.76,0.93,Ampicillin,25.4
9,S010,L. monocytogenes,Water,LB Agar,25,7.16,24,184,0.53,1.08,Ampicillin,19.2

**A DataFrame is essentially a table containing rows and columns.**

In [ ]:
#printing dataset size
data.shape

(30, 12)

In [ ]:
#printing columns
data.columns

Index(['Sample_ID', 'Organism', 'Sample_Type', 'Growth_Media', 'Temperature_C',
       'pH', 'Incubation_Hours', 'Colony_Count', 'Growth_Rate', 'OD600',
       'Antibiotic', 'Zone_Diameter_mm'],
      dtype='object')

In [ ]:
#printing the details of the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Sample_ID         30 non-null     object
 1   Organism          30 non-null     object
 2   Sample_Type       30 non-null     object
 3   Growth_Media      30 non-null     object
 4   Temperature_C     30 non-null     int64
 5   pH                30 non-null     float64
 6   Incubation_Hours  30 non-null     int64
 7   Colony_Count      30 non-null     int64
 8   Growth_Rate       30 non-null     float64
 9   OD600             30 non-null     float64
 10  Antibiotic        30 non-null     object
 11  Zone_Diameter_mm  30 non-null     float64
dtypes: float64(4), int64(3), object(5)
memory usage: 2.9+ KB

In [ ]:
#To print statistical summary
data.describe()

,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Zone_Diameter_mm
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,33.466667,6.827000,33.800000,179.666667,0.845667,1.102333,21.120000
std,7.491298,0.682486,11.842064,65.006808,0.243816,0.268645,3.596588
min,25.000000,5.600000,18.000000,21.000000,0.490000,0.460000,15.200000
25%,25.000000,6.250000,24.000000,132.000000,0.617500,0.940000,19.200000
50%,37.000000,6.945000,36.000000,181.500000,0.870000,1.085000,20.200000
75%,42.000000,7.270000,48.000000,242.750000,0.995000,1.270000,24.075000
max,42.000000,7.930000,48.000000,287.000000,1.290000,1.610000,29.700000

Selecting Columns

In [ ]:
data["Organism"]

0        P. aeruginosa
1     L. monocytogenes
2          B. subtilis
3     L. monocytogenes
4     L. monocytogenes
5            S. aureus
6          B. subtilis
7          B. subtilis
8          B. subtilis
9     L. monocytogenes
10       P. aeruginosa
11         B. subtilis
12    L. monocytogenes
13           S. aureus
14       P. aeruginosa
15           S. aureus
16       P. aeruginosa
17    L. monocytogenes
18             E. coli
19       P. aeruginosa
20           S. aureus
21    L. monocytogenes
22       P. aeruginosa
23             E. coli
24             E. coli
25         B. subtilis
26         B. subtilis
27           S. aureus
28       P. aeruginosa
29       P. aeruginosa
Name: Organism, dtype: object

In [ ]:
data["Colony_Count"]

0     250
1     209
2     244
3     140
4     135
5     252
6     278
7     217
8     156
9     184
10    244
11    253
12    191
13    171
14    179
15    115
16    252
17    199
18    132
19     71
20    287
21    132
22    120
23    132
24    100
25    206
26    132
27     21
28    149
29    239
Name: Colony_Count, dtype: int64

In [ ]:
data[["Sample_ID", "Organism", "Colony_Count"]]

   Sample_ID          Organism  Colony_Count
0       S001     P. aeruginosa           250
1       S002  L. monocytogenes           209
2       S003       B. subtilis           244
3       S004  L. monocytogenes           140
4       S005  L. monocytogenes           135
5       S006         S. aureus           252
6       S007       B. subtilis           278
7       S008       B. subtilis           217
8       S009       B. subtilis           156
9       S010  L. monocytogenes           184
10      S011     P. aeruginosa           244
11      S012       B. subtilis           253
12      S013  L. monocytogenes           191
13      S014         S. aureus           171
14      S015     P. aeruginosa           179
15      S016         S. aureus           115
16      S017     P. aeruginosa           252
17      S018  L. monocytogenes           199
18      S019           E. coli           132
19      S020     P. aeruginosa            71
20      S021         S. aureus           287
21      S022  L. monocytogenes           132
22      S023     P. aeruginosa           120
23      S024           E. coli           132
24      S025           E. coli           100
25      S026       B. subtilis           206
26      S027       B. subtilis           132
27      S028         S. aureus            21
28      S029     P. aeruginosa           149
29      S030     P. aeruginosa           239

In [ ]:
#printing the average colony count
data["Colony_Count"].mean()

np.float64(179.66666666666666)

In [ ]:
#printing the average growth rate
data["Growth_Rate"].mean()

np.float64(0.8456666666666668)

In [ ]:
data["OD600"].mean()

np.float64(1.1023333333333334)

In [ ]:
data["Colony_Count"].min()

21

In [ ]:
data["Colony_Count"].max()

287

In [ ]:
#Selecting Rows
data.iloc[0]

Sample_ID                    S001
Organism            P. aeruginosa
Sample_Type                  Food
Growth_Media              LB Agar
Temperature_C                  37
pH                           7.01
Incubation_Hours               36
Colony_Count                  250
Growth_Rate                  1.18
OD600                        1.45
Antibiotic           Tetracycline
Zone_Diameter_mm             19.2
Name: 0, dtype: object

In [ ]:
#Selecting Rows
data.iloc[0:5]

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
0,S001,P. aeruginosa,Food,LB Agar,37,7.01,36,250,1.18,1.45,Tetracycline,19.2
1,S002,L. monocytogenes,Clinical,LB Agar,25,7.82,36,209,0.60,1.24,Gentamicin,19.9
2,S003,B. subtilis,Clinical,LB Agar,42,7.13,18,244,0.96,1.27,Gentamicin,19.3
3,S004,L. monocytogenes,Soil,LB Agar,30,7.79,48,140,0.71,0.81,Tetracycline,21.9
4,S005,L. monocytogenes,Food,Mannitol Salt Agar,25,7.63,18,135,0.69,0.94,Ampicillin,16.5

In [ ]:
#Specific rows and columns
data.iloc[0:5, 0:3]

  Sample_ID          Organism Sample_Type
0      S001     P. aeruginosa        Food
1      S002  L. monocytogenes    Clinical
2      S003       B. subtilis    Clinical
3      S004  L. monocytogenes        Soil
4      S005  L. monocytogenes        Food

In [ ]:
#Selecting data based on a condition
data[data["Temperature_C"] > 30]

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
0,S001,P. aeruginosa,Food,LB Agar,37,7.01,36,250,1.18,1.45,Tetracycline,19.2
2,S003,B. subtilis,Clinical,LB Agar,42,7.13,18,244,0.96,1.27,Gentamicin,19.3
5,S006,S. aureus,Fermentation,LB Agar,42,6.62,48,252,1.00,1.43,Tetracycline,19.2
6,S007,B. subtilis,Food,Nutrient Agar,42,5.74,36,278,0.91,1.52,Ampicillin,22.6
7,S008,B. subtilis,Fermentation,MacConkey Agar,42,6.43,36,217,0.85,1.27,Gentamicin,20.1
11,S012,B. subtilis,Soil,LB Agar,37,6.19,24,253,1.29,1.40,Gentamicin,17.9
15,S016,S. aureus,Soil,LB Agar,37,7.62,18,115,1.10,0.93,Tetracycline,28.8
17,S018,L. monocytogenes,Fermentation,Mannitol Salt Agar,42,6.09,24,199,0.89,1.24,Tetracycline,16.2
19,S020,P. aeruginosa,Clinical,Mannitol Salt Agar,42,5.60,48,71,0.87,0.60,Tetracycline,21.5
20,S021,S. aureus,Clinical,LB Agar,42,7.28,48,287,0.87,1.61,Gentamicin,15.2
21,S022,L. monocytogenes,Clinical,MacConkey Agar,42,5.78,48,132,0.98,0.96,Ampicillin,24.8
22,S023,P. aeruginosa,Clinical,Mannitol Salt Agar,37,6.60,48,120,1.10,0.96,Ampicillin,22.8
23,S024,E. coli,Fermentation,Nutrient Agar,37,6.00,24,132,1.07,1.09,Ampicillin,20.3
24,S025,E. coli,Food,LB Agar,37,7.74,24,100,1.19,0.81,Ampicillin,24.5
26,S027,B. subtilis,Clinical,Nutrient Agar,42,6.91,48,132,0.98,0.85,Ampicillin,29.7
27,S028,S. aureus,Water,Mannitol Salt Agar,37,7.24,24,21,1.28,0.46,Gentamicin,24.8
28,S029,P. aeruginosa,Clinical,Nutrient Agar,37,5.85,36,149,0.96,0.98,Gentamicin,20.4

In [ ]:
#slecting records where pH is < 7
data[data["pH"] < 7]

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
5,S006,S. aureus,Fermentation,LB Agar,42,6.62,48,252,1.00,1.43,Tetracycline,19.2
6,S007,B. subtilis,Food,Nutrient Agar,42,5.74,36,278,0.91,1.52,Ampicillin,22.6
7,S008,B. subtilis,Fermentation,MacConkey Agar,42,6.43,36,217,0.85,1.27,Gentamicin,20.1
10,S011,P. aeruginosa,Clinical,Mannitol Salt Agar,25,6.98,48,244,0.70,1.35,Ampicillin,16.6
11,S012,B. subtilis,Soil,LB Agar,37,6.19,24,253,1.29,1.40,Gentamicin,17.9
12,S013,L. monocytogenes,Clinical,LB Agar,25,6.90,24,191,0.57,1.25,Gentamicin,18.2
13,S014,S. aureus,Water,LB Agar,25,6.46,18,171,0.56,1.06,Ampicillin,19.0
17,S018,L. monocytogenes,Fermentation,Mannitol Salt Agar,42,6.09,24,199,0.89,1.24,Tetracycline,16.2
18,S019,E. coli,Water,MacConkey Agar,25,6.14,48,132,0.49,0.94,Ampicillin,25.4
19,S020,P. aeruginosa,Clinical,Mannitol Salt Agar,42,5.60,48,71,0.87,0.60,Tetracycline,21.5
21,S022,L. monocytogenes,Clinical,MacConkey Agar,42,5.78,48,132,0.98,0.96,Ampicillin,24.8
22,S023,P. aeruginosa,Clinical,Mannitol Salt Agar,37,6.60,48,120,1.10,0.96,Ampicillin,22.8
23,S024,E. coli,Fermentation,Nutrient Agar,37,6.00,24,132,1.07,1.09,Ampicillin,20.3
25,S026,B. subtilis,Soil,Mannitol Salt Agar,25,6.69,36,206,0.53,1.09,Tetracycline,21.1
26,S027,B. subtilis,Clinical,Nutrient Agar,42,6.91,48,132,0.98,0.85,Ampicillin,29.7
28,S029,P. aeruginosa,Clinical,Nutrient Agar,37,5.85,36,149,0.96,0.98,Gentamicin,20.4

In [ ]:
#colony coun >100
data[data["Colony_Count"] > 100]

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
0,S001,P. aeruginosa,Food,LB Agar,37,7.01,36,250,1.18,1.45,Tetracycline,19.2
1,S002,L. monocytogenes,Clinical,LB Agar,25,7.82,36,209,0.60,1.24,Gentamicin,19.9
2,S003,B. subtilis,Clinical,LB Agar,42,7.13,18,244,0.96,1.27,Gentamicin,19.3
3,S004,L. monocytogenes,Soil,LB Agar,30,7.79,48,140,0.71,0.81,Tetracycline,21.9
4,S005,L. monocytogenes,Food,Mannitol Salt Agar,25,7.63,18,135,0.69,0.94,Ampicillin,16.5
5,S006,S. aureus,Fermentation,LB Agar,42,6.62,48,252,1.00,1.43,Tetracycline,19.2
6,S007,B. subtilis,Food,Nutrient Agar,42,5.74,36,278,0.91,1.52,Ampicillin,22.6
7,S008,B. subtilis,Fermentation,MacConkey Agar,42,6.43,36,217,0.85,1.27,Gentamicin,20.1
8,S009,B. subtilis,Soil,LB Agar,25,7.17,36,156,0.76,0.93,Ampicillin,25.4
9,S010,L. monocytogenes,Water,LB Agar,25,7.16,24,184,0.53,1.08,Ampicillin,19.2
10,S011,P. aeruginosa,Clinical,Mannitol Salt Agar,25,6.98,48,244,0.70,1.35,Ampicillin,16.6
11,S012,B. subtilis,Soil,LB Agar,37,6.19,24,253,1.29,1.40,Gentamicin,17.9
12,S013,L. monocytogenes,Clinical,LB Agar,25,6.90,24,191,0.57,1.25,Gentamicin,18.2
13,S014,S. aureus,Water,LB Agar,25,6.46,18,171,0.56,1.06,Ampicillin,19.0
14,S015,P. aeruginosa,Water,Mannitol Salt Agar,25,7.93,24,179,0.57,0.96,Ampicillin,24.6
15,S016,S. aureus,Soil,LB Agar,37,7.62,18,115,1.10,0.93,Tetracycline,28.8
16,S017,P. aeruginosa,Water,MacConkey Agar,25,7.30,18,252,0.51,1.26,Ampicillin,19.2
17,S018,L. monocytogenes,Fermentation,Mannitol Salt Agar,42,6.09,24,199,0.89,1.24,Tetracycline,16.2
18,S019,E. coli,Water,MacConkey Agar,25,6.14,48,132,0.49,0.94,Ampicillin,25.4
20,S021,S. aureus,Clinical,LB Agar,42,7.28,48,287,0.87,1.61,Gentamicin,15.2
21,S022,L. monocytogenes,Clinical,MacConkey Agar,42,5.78,48,132,0.98,0.96,Ampicillin,24.8
22,S023,P. aeruginosa,Clinical,Mannitol Salt Agar,37,6.60,48,120,1.10,0.96,Ampicillin,22.8
23,S024,E. coli,Fermentation,Nutrient Agar,37,6.00,24,132,1.07,1.09,Ampicillin,20.3
25,S026,B. subtilis,Soil,Mannitol Salt Agar,25,6.69,36,206,0.53,1.09,Tetracycline,21.1
26,S027,B. subtilis,Clinical,Nutrient Agar,42,6.91,48,132,0.98,0.85,Ampicillin,29.7
28,S029,P. aeruginosa,Clinical,Nutrient Agar,37,5.85,36,149,0.96,0.98,Gentamicin,20.4
29,S030,P. aeruginosa,Water,LB Agar,25,7.01,48,239,0.67,1.33,Ampicillin,19.3

**DATE:- 19TH septemebr 2026**

TOPIC:- RETRIVING THE DATA BASED ON MULTIPLE CONDITIONS
SYNTAX:- & symbol

In [ ]:
import pandas as pd
data = pd.read_csv("dataset.csv")

In [ ]:
data[(data["Temperature_C"] >30) & (data["pH"] < 7)]

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
5,S006,S. aureus,Fermentation,LB Agar,42,6.62,48,252,1.00,1.43,Tetracycline,19.2
6,S007,B. subtilis,Food,Nutrient Agar,42,5.74,36,278,0.91,1.52,Ampicillin,22.6
7,S008,B. subtilis,Fermentation,MacConkey Agar,42,6.43,36,217,0.85,1.27,Gentamicin,20.1
11,S012,B. subtilis,Soil,LB Agar,37,6.19,24,253,1.29,1.40,Gentamicin,17.9
17,S018,L. monocytogenes,Fermentation,Mannitol Salt Agar,42,6.09,24,199,0.89,1.24,Tetracycline,16.2
19,S020,P. aeruginosa,Clinical,Mannitol Salt Agar,42,5.60,48,71,0.87,0.60,Tetracycline,21.5
21,S022,L. monocytogenes,Clinical,MacConkey Agar,42,5.78,48,132,0.98,0.96,Ampicillin,24.8
22,S023,P. aeruginosa,Clinical,Mannitol Salt Agar,37,6.60,48,120,1.10,0.96,Ampicillin,22.8
23,S024,E. coli,Fermentation,Nutrient Agar,37,6.00,24,132,1.07,1.09,Ampicillin,20.3
26,S027,B. subtilis,Clinical,Nutrient Agar,42,6.91,48,132,0.98,0.85,Ampicillin,29.7
28,S029,P. aeruginosa,Clinical,Nutrient Agar,37,5.85,36,149,0.96,0.98,Gentamicin,20.4

In [ ]:
# Q.write a code where colony count is greater than 250 and growth is greater than 1
data[(data["Colony_Count"]> 250) & (data["Growth_Rate"]>1 )]

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
11,S012,B. subtilis,Soil,LB Agar,37,6.19,24,253,1.29,1.4,Gentamicin,17.9

In [ ]:
#ph value less than 7 sample type is food

data[(data["pH"]<7)& (data["Sample_Type"]=="food")]

Empty DataFrame
Columns: [Sample_ID, Organism, Sample_Type, Growth_Media, Temperature_C, pH, Incubation_Hours, Colony_Count, Growth_Rate, OD600, Antibiotic, Zone_Diameter_mm]
Index: []

In [ ]:
# & means both the conditions must be satisfied
#| means that either of the stated condistions should be satisfied

In [ ]:
data[(data["Temperature_C"]>30) | (data["pH"]>7)]

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
0,S001,P. aeruginosa,Food,LB Agar,37,7.01,36,250,1.18,1.45,Tetracycline,19.2
1,S002,L. monocytogenes,Clinical,LB Agar,25,7.82,36,209,0.60,1.24,Gentamicin,19.9
2,S003,B. subtilis,Clinical,LB Agar,42,7.13,18,244,0.96,1.27,Gentamicin,19.3
3,S004,L. monocytogenes,Soil,LB Agar,30,7.79,48,140,0.71,0.81,Tetracycline,21.9
4,S005,L. monocytogenes,Food,Mannitol Salt Agar,25,7.63,18,135,0.69,0.94,Ampicillin,16.5
5,S006,S. aureus,Fermentation,LB Agar,42,6.62,48,252,1.00,1.43,Tetracycline,19.2
6,S007,B. subtilis,Food,Nutrient Agar,42,5.74,36,278,0.91,1.52,Ampicillin,22.6
7,S008,B. subtilis,Fermentation,MacConkey Agar,42,6.43,36,217,0.85,1.27,Gentamicin,20.1
8,S009,B. subtilis,Soil,LB Agar,25,7.17,36,156,0.76,0.93,Ampicillin,25.4
9,S010,L. monocytogenes,Water,LB Agar,25,7.16,24,184,0.53,1.08,Ampicillin,19.2
11,S012,B. subtilis,Soil,LB Agar,37,6.19,24,253,1.29,1.40,Gentamicin,17.9
14,S015,P. aeruginosa,Water,Mannitol Salt Agar,25,7.93,24,179,0.57,0.96,Ampicillin,24.6
15,S016,S. aureus,Soil,LB Agar,37,7.62,18,115,1.10,0.93,Tetracycline,28.8
16,S017,P. aeruginosa,Water,MacConkey Agar,25,7.30,18,252,0.51,1.26,Ampicillin,19.2
17,S018,L. monocytogenes,Fermentation,Mannitol Salt Agar,42,6.09,24,199,0.89,1.24,Tetracycline,16.2
19,S020,P. aeruginosa,Clinical,Mannitol Salt Agar,42,5.60,48,71,0.87,0.60,Tetracycline,21.5
20,S021,S. aureus,Clinical,LB Agar,42,7.28,48,287,0.87,1.61,Gentamicin,15.2
21,S022,L. monocytogenes,Clinical,MacConkey Agar,42,5.78,48,132,0.98,0.96,Ampicillin,24.8
22,S023,P. aeruginosa,Clinical,Mannitol Salt Agar,37,6.60,48,120,1.10,0.96,Ampicillin,22.8
23,S024,E. coli,Fermentation,Nutrient Agar,37,6.00,24,132,1.07,1.09,Ampicillin,20.3
24,S025,E. coli,Food,LB Agar,37,7.74,24,100,1.19,0.81,Ampicillin,24.5
26,S027,B. subtilis,Clinical,Nutrient Agar,42,6.91,48,132,0.98,0.85,Ampicillin,29.7
27,S028,S. aureus,Water,Mannitol Salt Agar,37,7.24,24,21,1.28,0.46,Gentamicin,24.8
28,S029,P. aeruginosa,Clinical,Nutrient Agar,37,5.85,36,149,0.96,0.98,Gentamicin,20.4
29,S030,P. aeruginosa,Water,LB Agar,25,7.01,48,239,0.67,1.33,Ampicillin,19.3

In [ ]:
#fileter the records where incubation hrs is > than 20 and antibiotic is = tetracycline

data[(data["Incubation_Hours"]> 20 | (data["Antibiotic"]=="Tetracycline"))]

#CHECK THIS ... WRONG ANSWER

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
0,S001,P. aeruginosa,Food,LB Agar,37,7.01,36,250,1.18,1.45,Tetracycline,19.2
1,S002,L. monocytogenes,Clinical,LB Agar,25,7.82,36,209,0.60,1.24,Gentamicin,19.9
2,S003,B. subtilis,Clinical,LB Agar,42,7.13,18,244,0.96,1.27,Gentamicin,19.3
3,S004,L. monocytogenes,Soil,LB Agar,30,7.79,48,140,0.71,0.81,Tetracycline,21.9
4,S005,L. monocytogenes,Food,Mannitol Salt Agar,25,7.63,18,135,0.69,0.94,Ampicillin,16.5
5,S006,S. aureus,Fermentation,LB Agar,42,6.62,48,252,1.00,1.43,Tetracycline,19.2
6,S007,B. subtilis,Food,Nutrient Agar,42,5.74,36,278,0.91,1.52,Ampicillin,22.6
7,S008,B. subtilis,Fermentation,MacConkey Agar,42,6.43,36,217,0.85,1.27,Gentamicin,20.1
8,S009,B. subtilis,Soil,LB Agar,25,7.17,36,156,0.76,0.93,Ampicillin,25.4
9,S010,L. monocytogenes,Water,LB Agar,25,7.16,24,184,0.53,1.08,Ampicillin,19.2
10,S011,P. aeruginosa,Clinical,Mannitol Salt Agar,25,6.98,48,244,0.70,1.35,Ampicillin,16.6
11,S012,B. subtilis,Soil,LB Agar,37,6.19,24,253,1.29,1.40,Gentamicin,17.9
12,S013,L. monocytogenes,Clinical,LB Agar,25,6.90,24,191,0.57,1.25,Gentamicin,18.2
13,S014,S. aureus,Water,LB Agar,25,6.46,18,171,0.56,1.06,Ampicillin,19.0
14,S015,P. aeruginosa,Water,Mannitol Salt Agar,25,7.93,24,179,0.57,0.96,Ampicillin,24.6
15,S016,S. aureus,Soil,LB Agar,37,7.62,18,115,1.10,0.93,Tetracycline,28.8
16,S017,P. aeruginosa,Water,MacConkey Agar,25,7.30,18,252,0.51,1.26,Ampicillin,19.2
17,S018,L. monocytogenes,Fermentation,Mannitol Salt Agar,42,6.09,24,199,0.89,1.24,Tetracycline,16.2
18,S019,E. coli,Water,MacConkey Agar,25,6.14,48,132,0.49,0.94,Ampicillin,25.4
19,S020,P. aeruginosa,Clinical,Mannitol Salt Agar,42,5.60,48,71,0.87,0.60,Tetracycline,21.5
20,S021,S. aureus,Clinical,LB Agar,42,7.28,48,287,0.87,1.61,Gentamicin,15.2
21,S022,L. monocytogenes,Clinical,MacConkey Agar,42,5.78,48,132,0.98,0.96,Ampicillin,24.8
22,S023,P. aeruginosa,Clinical,Mannitol Salt Agar,37,6.60,48,120,1.10,0.96,Ampicillin,22.8
23,S024,E. coli,Fermentation,Nutrient Agar,37,6.00,24,132,1.07,1.09,Ampicillin,20.3
24,S025,E. coli,Food,LB Agar,37,7.74,24,100,1.19,0.81,Ampicillin,24.5
25,S026,B. subtilis,Soil,Mannitol Salt Agar,25,6.69,36,206,0.53,1.09,Tetracycline,21.1
26,S027,B. subtilis,Clinical,Nutrient Agar,42,6.91,48,132,0.98,0.85,Ampicillin,29.7
27,S028,S. aureus,Water,Mannitol Salt Agar,37,7.24,24,21,1.28,0.46,Gentamicin,24.8
28,S029,P. aeruginosa,Clinical,Nutrient Agar,37,5.85,36,149,0.96,0.98,Gentamicin,20.4
29,S030,P. aeruginosa,Water,LB Agar,25,7.01,48,239,0.67,1.33,Ampicillin,19.3

In [ ]:
#combining the conditions:-

data[(data["Organism"]=="E. coli") & (data["Antibiotic"]=="Ampicillin")]

,Sample_ID,Organism,Sample_Type,Growth_Media,Temperature_C,pH,Incubation_Hours,Colony_Count,Growth_Rate,OD600,Antibiotic,Zone_Diameter_mm
18,S019,E. coli,Water,MacConkey Agar,25,6.14,48,132,0.49,0.94,Ampicillin,25.4
23,S024,E. coli,Fermentation,Nutrient Agar,37,6.00,24,132,1.07,1.09,Ampicillin,20.3
24,S025,E. coli,Food,LB Agar,37,7.74,24,100,1.19,0.81,Ampicillin,24.5